columnSuffix: null
contentColumnType: string
fieldGroup: b9f3295d-0343-46eb-83ed-b4adc72c4de1 # Home Page
handle: content2Box
instructions: ''
name: Content-2-Box
searchable: false
settings:
  contentTable: '{{%matrixcontent_content2box}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
