columnSuffix: null
contentColumnType: string
fieldGroup: b9f3295d-0343-46eb-83ed-b4adc72c4de1 # Home Page
handle: content6List
instructions: ''
name: Content-6-List
searchable: false
settings:
  contentTable: '{{%matrixcontent_content6list}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
