columnSuffix: null
contentColumnType: string
fieldGroup: 7cfc6a92-9a09-44e3-95e4-abf5ba7b040b # Header
handle: navLinks
instructions: ''
name: 'Nav Links'
searchable: false
settings:
  contentTable: '{{%matrixcontent_navlinks}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
