defaultPlacement: end
enableVersioning: true
handle: ourStory
name: 'Our Story'
propagationMethod: all
siteSettings:
  3265eae9-6ce5-4cbb-99e3-bf637409fb48: # Slama
    enabledByDefault: true
    hasUrls: true
    template: 'page\our story\index'
    uriFormat: our-story
type: single
